name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Deploy to Firebase
        uses: lowply/deploy-firebase@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}